### ISSUE TITLE
I cannot upload it.

### ISSUE THREAD

**Issue by hellokeanu** [cowden/Turk#1]

**Comment by cowden** [comment]
@hellokeanu 

I added you as a collaborator.  You should be able to commit to the repository.Let me know if 
1) you got the invite, and
2) if you are able to push your code to the repo.

**Comment by hellokeanu** [comment]
I get the invite.

I will test the push before I sleep.

Thank you

Best Regards

2016-06-26 23:03 GMT-05:00 Christopher Cowden notifications@github.com:

**Comment by cowden** [comment]
Looks like this is a solved problem.  I'm closing the issue.

**Comment by hellokeanu** [comment]
This is also a cool function.

2016-07-06 11:12 GMT-05:00 Christopher Cowden notifications@github.com:
